[package]
name = "talking-airplane"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindings = { path = "../bindings" }
msfs = "0.0.1-alpha.2"
clap = "3.0.0-beta.4"